In [1]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [2]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [3]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[88, 62, 56, 90, 84]

In [4]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([94, 99, 58, 52, 83])

In [5]:
np.random.randint(50,high=100,size=(50, 5))

array([[91, 57, 52, 84, 50],
       [64, 95, 66, 81, 52],
       [62, 97, 50, 70, 83],
       [91, 55, 76, 56, 90],
       [84, 62, 75, 98, 50],
       [87, 78, 87, 72, 51],
       [55, 67, 95, 84, 71],
       [91, 50, 91, 56, 91],
       [66, 63, 93, 75, 69],
       [88, 59, 54, 55, 75],
       [84, 77, 66, 52, 64],
       [97, 69, 51, 76, 69],
       [91, 91, 89, 94, 86],
       [63, 52, 83, 51, 93],
       [55, 80, 85, 67, 67],
       [69, 58, 63, 69, 90],
       [57, 68, 89, 91, 92],
       [71, 72, 86, 84, 73],
       [75, 66, 73, 74, 73],
       [91, 92, 64, 50, 65],
       [64, 82, 91, 55, 72],
       [71, 72, 76, 57, 50],
       [91, 80, 77, 68, 89],
       [77, 78, 69, 51, 53],
       [57, 87, 84, 99, 51],
       [61, 74, 82, 89, 92],
       [91, 97, 86, 62, 89],
       [96, 82, 63, 84, 53],
       [62, 80, 85, 79, 91],
       [75, 88, 95, 74, 91],
       [93, 78, 71, 67, 83],
       [77, 73, 71, 92, 90],
       [76, 93, 68, 95, 52],
       [69, 67, 94, 84, 68],
       [69, 98